apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-dashboard
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-dashboard
  template:
    metadata:
      labels:
        app: backend-dashboard
    spec:
      containers:
        - name: backend-dashboard
          image: backend-dashboard:latest
          ports:
            - containerPort: 8000
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka:9092"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: backend-dashboard
  namespace: kafka
spec:
  selector:
    app: backend-dashboard
  ports:
    - port: 8000
      targetPort: 8000
  type: ClusterIP
