apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: data-pipeline-cluster
  namespace: kafka
spec:
  kafka:
    replicas: 1
    version: 3.4.0
    storage:
      type: ephemeral
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
  zookeeper:
    replicas: 1
    storage:
      type: ephemeral
  entityOperator:
    topicOperator: {}
    userOperator: {}
