apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: documents
  namespace: kafka
  labels:
    strimzi.io/cluster: data-pipeline-cluster
spec:
  partitions: 3
  replicas: 1
  config:
    retention.ms: 604800000
    segment.bytes: 1073741824
